export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
import Footer from "@/components/Footer/Footer"
import Header from "@/components/Header/Header"
import "@/styles/global.css"

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
     
     <Header/>
      {children}
      <Footer/>
      </body>
    </html>
  )
}
